In [1]:
import numpy as np
from io import BytesIO

In [60]:
with open('resources/poza_rgb.shape', "rb") as f:
    shape = int.from_bytes(f.read(4), 'little'), int.from_bytes(f.read(4), 'little')

img_r = np.fromfile('resources/poza_rgb.r', dtype=np.uint8).reshape(shape)
img_g = np.fromfile('resources/poza_rgb.g', dtype=np.uint8).reshape(shape)
img_b = np.fromfile('resources/poza_rgb.b', dtype=np.uint8).reshape(shape)

img = np.array([img_r, img_g, img_b]).transpose((1, 2, 0))
print(img)

[[[249 249 249]
  [249 249 249]
  [249 249 249]
  ...
  [249 249 249]
  [249 249 249]
  [249 249 249]]

 [[249 249 249]
  [249 249 249]
  [249 249 249]
  ...
  [249 249 249]
  [249 249 249]
  [249 249 249]]

 [[249 249 249]
  [249 249 249]
  [249 249 249]
  ...
  [249 249 249]
  [249 249 249]
  [249 249 249]]

 ...

 [[249 249 249]
  [249 249 249]
  [249 249 249]
  ...
  [247 249 249]
  [247 249 249]
  [247 249 249]]

 [[249 249 249]
  [249 249 249]
  [249 249 249]
  ...
  [247 249 249]
  [247 249 249]
  [247 249 249]]

 [[247 249 249]
  [247 249 249]
  [247 249 249]
  ...
  [247 249 249]
  [247 249 249]
  [247 249 249]]]
